### ISSUE TITLE
fixing issues

### ISSUE THREAD

**Issue by aiegoo** [aiegoo/_capev2#3]
## capev2Mosa ip

```
network:
  version: 2
  ethernets:
    enp1s0:
      dhcp4: no
      addresses: [192.168.122.150/24]
      gateway4: 192.168.122.1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]

```
at /etc/netplan/01-netcfg.yml
